version: '3.1'

services:
  cardano-node:
    image: inputoutput/cardano-node:1.35.5
    container_name: cardano-node
    volumes:
      - ./cardano-node-ipc:/ipc
      - ./cardano-node-data:/data
      - ./configuration:/configuration
      - ./cardano-wallet:/cardano-wallet
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
      - CARDANO_CLI=/cardano-wallet/cardano-cli
      - DOCKER_CLIENT_TIMEOUT=120
      - COMPOSE_HTTP_TIMEOUT=120
      - NETWORK=mainnet
      - HOST-ADDR="0.0.0.0"
    #ports:
    #  - "3001:3001"
    restart: unless-stopped
    networks:
      - cardano-node-net

  #socat-cardano-node:
  #  image: alpine/socat
  #  container_name: socat-cardano-node
  #  volumes:
  #    - ./cardano-node-ipc:/ipc
  #  command: "TCP-LISTEN:3001,fork,reuseaddr, UNIX-CONNECT:/ipc/node.socket"
  #  ports:
  #    - "3001:3001"
  #  restart: unless-stopped
  #  networks:
  #    - cardano-node-net

networks:
  cardano-node-net:
    name: cardano-node-net
    driver: bridge
